name: Setup Pulumi
description: Install Pulumi for use in Buildkite builds
author: https://github.com/praneetloke
requirements:
  - curl
  - bash
configuration:
  properties:
    version:
      type: string
    install_root:
      type: string
